runtime: php72

runtime_config:
  document_root: public

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:/jqHjcdGhSeC14g3rbGQh6Cbc5YkHJ1b/DbXcQD/xbs=
  APP_LOG: errorlog
  #  CACHE_DRIVER: database
  #  SESSION_DRIVER: database
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  #  CACHE_DRIVER: database
  #  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_CONNECTION: mysql
  DB_DATABASE: foodomaa
  DB_USERNAME: root
  DB_PASSWORD: ahcyT1234#A
  QUEUE_DRIVER: database
  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/acehost:us-central1:acefun-times"
  ## for PostgreSQL, use DB_HOST:
  #  DB_HOST: "/cloudsql/acehost:us-central1:acefun-times"
