image: php:7.2-fpm

pipelines:
  default:
    - step:
        script:
          - pipe: atlassian/google-cloud-storage-deploy:0.4.4
            variables:
              KEY_FILE: 'ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiYWNlZnVuIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiNjkwOWFiNTliZmU4MWM3MjFkYzFhMzMxYTVmOTY1Y2ViYjU5NDU5MCIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2d3Z2dTa0FnRUFBb0lCQVFDOWI0WElrQnZubGliTVxuUTBRaHFGSVg3bkNXRXVGTXlKZGg0SzhhYUgrY08xREpzckFLYW9HSitnaHo3anN1RFk5MzdDelVWL0x4S3NkcVxuREpyNlhGWW9pRnMzZ1AyQU92c1hBTEozcXFYWTRRYkw2YmpoTTdXUDJ1bFJRMmJzL09rdjR4RXJrYjltR01mUlxuSGpCYk5xbjZtSXpIZkd6dmV4ZGtwdXlPMUV5ZTZtSHVld2x1ZDRENnlUN1ozcytFSlJPUjNjc2hPYkRjRXdOSlxucHZjWjVqS2ppY1JBRzJJeHN5UjRxRzRMT3VXVnA3NUhLN0VCTDVldmVnN01OR2cxM05CcTN4Rk9qTGFXYjRpdVxuTE9zeG1zMm83dnBoZEdLZUp6VEVLajBKeGhwejVVRkRoWkhxVEFacjhwUVdKeStFL2VKQ1NIMUQ3eFJKT3hFelxudUxBczNVa2xBZ01CQUFFQ2dnRUFEVHVYR3RXR1BYMHRwS01tUlR1ZTBIRWxpRFkxYXNtd1dYUDZoMXU1WGs1K1xuYkRpQk41a05CM2hoMHNkWGR2WVhpWWNEOHFsYUhTS2gzM1NWOXRzd1laQjAzc0d4ODUwcklRWTVjVWFJWTBnRVxuMDRXMkZuVW9QNjVKRWhZbFFIVENUVWdOVVAvVFlPeG1PT05rK1ZvdU1ZVXFnRnpldHpQZ0JIWHNuR1dVSEoyZlxudTlzeUVvL2N4OE4zbW9zWHB5dzRIUXd3T3ZpQ2JkZ2o1TnowNXJuNnZMbUtrWm8veGM0elFTMmowS1ZEQXlPNFxuKzhZMmVZaklFMUZJcW1GTVNaSWtYS2E1bGZGU1JrL2ZwMUlVN3h6OUUyMHdrb1N2RlZHYng0enJpY0JwUjBnR1xuZStZeTVtbXA1RGhZTzRHdWo1U1JDZ1F1c25YdjZ1eWlSTkxEbkFrU0dRS0JnUUQ5WU9vRkE0UXFCUGxGbVdObVxub2svbldsWStSSENoS3JLQy8vaXQrWUMyR1pZU2hTUkVVaDg5WE5RODlsblZLQkp6a2lBNFIrTGt6NS9NQUViMVxuWGdnTkUxc3hPU1hZTW15QTRVMS9iaCsrY1A0WXdKMlNsemZjOGdKSjNaQTJMVldHeEFMT2t1Y3NSbFQ0SFNQK1xuRWhjcGwwbXZZWi9uZ24xSlFDWTVieDJ0M3dLQmdRQy9aVUNiM0pVMU5LYjJ5blBuemd0WHcyeHA1MTVtZGRpK1xuTU00UHFLM2dYemE1dUFNQnI5THJ1cGN2RFhBRGkwcVRpdTBtTTF1WVhPeTNJTkRIeXRWd0ZzK3daeHNIa1drSFxubnlVeHc1ak1VTUVnUmtwNkJjY2hvRHlVUzZQaVI1dGZkeFdzMDlicFFIR2hrcTh5dUdiM1lJM09oT05YT2lEcVxuYmFTT3ZlOGhld0tCZ0VBUEZYdEpCVXYrVCtzNXVYakVSb0ZPUkltZmtmNGRKbDZhU292cGpaSDhiQVdvcFora1xuUjRPakNZR1VJdWdTSm9BVGpKUE9FTjRhWStNV210b0QrUE1kVnF2ZUwrUTE4MXF1RzRMQkc4TnhHN3kwVGVJMlxuMndmQUk3WDdEeSt6VEhFeTh5YTQyenRGV013VnlmaTlLQi82d01WWFlDOE92WkFjYU0yU2V5VnZBb0dCQUpLRVxuZHBOYXA3YVZXZ092TkUrT0FrenJRNEZISjVNVVFCcEl6bFphY05GRTBtWVdJZWNXckViZERvTnNyQVZxaW1xc1xuZmFNeXlibTMyVmJQZmtTVVdCUjR3Z0Z1ek5oY1RxVVJCYTQwNkRIdzJBZFhDQWlsaDYyTU54UG5XOHdMdVR1NVxudEJRY0QzZDhhQUNpaEJBMTdrME4wMEQzcGZuT2ZBZzZhekVDNFo4bEFvR0JBSmFoVlVadFRJekFGemZLOWlsUVxuWktJLzFoNE1IdC93NVc5QWVYU3l2NFhKVE9LTCtWa3kxSGlVYk5ScjZ2aUxVN3MrYjlwUEh4L0tCTHpFaWo4dFxuU0o2QkFSRm9NWUpDazJBb2hNSnFmQTRRSlp4dkZwdVM5ZFo4MHRkU0E0VWxpTVRJZ1llbDBhR2QrRG9EYkswTVxuYTRvVmxTNmhJVTlqU2hZQmNYOTRQU2UvXG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiYWNlLWRlcGxveUBhY2VmdW4uaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA1MTkyOTI1Njk4MTQ0ODE1MDc5IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9hY2UtZGVwbG95JTQwYWNlZnVuLmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9Cg=='
              PROJECT: 'acefun'
              BUCKET: 'acefun'
              SOURCE: '.'
              # CACHE_CONTROL: '<string>' # Optional.
              # CONTENT_DISPOSITION: '<string>' # Optional.
              # CONTENT_ENCODING: '<string>' # Optional.
              # CONTENT_LANGUAGE: '<string>' # Optional.
              # CONTENT_TYPE: '<string>' # Optional.
              # ACL: '<string>' # Optional.
              # STORAGE_CLASS: '<string>' # Optional.
              # EXTRA_ARGS: '<string>' # Optional.
              # DEBUG: '<boolean>' # Optional.
        services:
          - mysql

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'foodomaa'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'ahcyT1234#A'
